### ISSUE TITLE
[BUG]: On nvidia wayland the launcher never finishes steam and steam does nothing

### ISSUE THREAD

**Issue by Salvodif** [DeckCheatz/wemod-launcher#108]
### Describe the bug

I just changed game (Hades) and doesn't starts anymore nor game nor wemod

    x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.555.58.02 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32:/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/panorama:/app/utils/steamtinkerlaunch/lib:/app/lib/i386-linux-gnu/GL/default/lib:/app/lib/i386-linux-gnu/GL/nvidia-555-58-02/lib:/app/lib/ffmpeg/.:/app/lib32/ffmpeg/.:/app/lib32:/app/lib/i386-linux-gnu:/lib64:/app/lib:/usr/lib/x86_64-linux-gnu/GL/default/lib:/usr/lib/x86_64-linux-gnu/GL/nvidia-555-58-02/lib:/usr/lib/x86_64-linux-gnu", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
    F: Not sharing "/usr/lib/git-core" with sandbox: Path "/usr" is reserved by Flatpak
    F: Not sharing "/usr/bin/git" with sandbox: Path "/usr" is reserved by Flatpak
    F: Not sharing "/usr/share/git" with sandbox: Path "/usr" is reserved by Flatpak
    wine: using kernel write watches, use_kernel_writewatch 1.
    fsync: up and running.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
    DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    wine: using kernel write watches, use_kernel_writewatch 1.
    chdir "/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Hades/x64/"
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    Adding process 2066 for gameID 1145360
    WARNING: discarding _NET_WM_PID 1569 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
    Adding process 2067 for gameID 1145360
    Adding process 2068 for gameID 1145360
    Adding process 2069 for gameID 1145360
    Adding process 2072 for gameID 1145360
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    /app/utils/steamtinkerlaunch/libexec/git-core/git-remote-https: symbol lookup error: /app/utils/steamtinkerlaunch/libexec/git-core/git-remote-https: undefined symbol: curl_global_sslset
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    Adding process 2073 for gameID 1145360
    Adding process 2074 for gameID 1145360
    ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    Adding process 2076 for gameID 1145360
    Adding process 2077 for gameID 1145360
    Adding process 2078 for gameID 1145360
    Adding process 2080 for gameID 1145360

### Steps to reproduce the behavior

launch the game after everything had been configured

### Expected behavior

I was expecting the WeMod start screen but it does not appear

### Logs

[wemod.log](https://github.com/user-attachments/files/16398328/wemod.log)

### System Information

OS: EndeavourOS
Linux KERNEL: 6.6.34-1-lts
CPU: 13th Gen Intel Core i5-13600K
GPU: NVIDIA GeForce RTX 3070 Ti
GPU DRIVER: NVIDIA 550.90.07
RAM: 32 GB

**Comment by marvin1099** [comment]
Please delete the log and retry and send the new log file so i only get the relevant logs.

**Comment by Salvodif** [comment]
[wemod.log](https://github.com/user-attachments/files/16467218/wemod.log)

**Comment by marvin1099** [comment]
So im not shure why its not working,
is this the only game with that Problem.
Right now i also in holiday so i havent looked at the code for a bit. For now i'm not shure about that Problem.

**Comment by Salvodif** [comment]
> So im not shure why its not working, is this the only game with that Problem. Right now i also in holiday so i havent looked at the code for a bit. For now i'm not shure about that Problem.

take your time and enjoy your holiday

**Comment by marvin1099** [comment]
So I marked this with help wanted, then someone else may help, but I'm out of ideas sadly.
Sorry that I have no ideas.

**Comment by Salvodif** [comment]
Have you seen the log and have no idea out it? :-o

**Comment by marvin1099** [comment]
The log looks normal, 
the only thing that i still have is the idea that it gets stuck on something,
but i have no idea what causes this.
The thing is that this appeares just on this game
so the script should be normal, 
the game really makes no functional difference,  
thats why I have no ideas.

Well maby try without any game arguments, that may do something or not.

**Comment by marvin1099** [comment]
Ok this issue seems very strange, as we have discussed it will try to solve this.
@calvyb and @Salvodif since it seems you have the same problem, both  of you can post what i ask for.
This is mostly in case it is a other issue.
First close steam, then open a terminal, then type "steam", next delete the wemod.log file, next start the wemod desired game, after that post the steam terminal output and the wemod.log file.
Please upload the steam terminal output as a file so this chat dosn't get spammed.
So save the steam terminal output in a file and drag it to the github comment box.
Also upload the wemod.log as file.
Lastly i know you have uploaded some of this already but i have pushed a update,
so just re-post the new outputs please.

**Comment by calvyb** [comment]
[konsole.txt](https://github.com/user-attachments/files/16663783/konsole.txt)
[wemod.log](https://github.com/user-attachments/files/16663786/wemod.log)
I hope these are helpful to you and what you asked for. i had do to the konsole twice as the first time i left it running so long it wouldnt export the whole thing.

**Comment by marvin1099** [comment]
run:
```
cd /home/$USER/wemod-launcher
git reset --hard origin
git pull
sudo chmod -R ug+x .
```
and if there is no error repeat the steps below

> First close steam,
   then open a terminal, 
   then type "steam", 
   next delete the wemod.log file,
   next start the wemod desired game,
   after that post the steam terminal output and the wemod.log file. 
   Please upload the steam terminal output as a file so this chat dosn't get spammed.
   So save the steam terminal output in a file and drag it to the github comment box.
   Also upload the wemod.log as file.

**Comment by calvyb** [comment]
Done all that. had to add /home/$user/wemod-launcher to the chmod command.

we mod still freezing on game launch
[konsole.txt](https://github.com/user-attachments/files/16665067/konsole.txt)
[wemod.log](https://github.com/user-attachments/files/16665086/wemod.log)

**Comment by marvin1099** [comment]
Jep sadly same thing as this issue,
this means i have no idea how to fix this,
sorry you can try a other game,
but other then then that i have no idea.

**Comment by marvin1099** [comment]
Considering that steam is doing nothing when the wemod launcher tryes to run it,
then if both of you still have this problem try to reinstall steam.
Also remove the .steam folder, but if you try that i recommend you to
move your `.steam/steam/steamapps/common` and your `.steam/steam/steamapps/sourcemods`
folders beforehand if you don't want to reinstall the games you have.
After the steam reinstall move the 2 folders back, steam will think that the games are not installed but when you click on install it will then say, `discovering old files`, and find the old game files.

**Comment by marvin1099** [comment]
> Considering that steam is doing nothing when the wemod launcher tryes to run it, then if both of you still have this problem try to reinstall steam. Also remove the .steam folder, but if you try that i recommend you to move your `.steam/steam/steamapps/common` and your `.steam/steam/steamapps/sourcemods` folders beforehand if you don't want to reinstall the games you have. After the steam reinstall move the 2 folders back, steam will think that the games are not installed but when you click on install it will then say, `discovering old files`, and find the old game files.

If you @Salvodif  or you @calvyb have tried this, report back if this has worked.

**Comment by calvyb** [comment]
Tried that and had no joy. same issue persists. had a spare 120g SSD so decided i'd try a totally clean arch (kde) install on that and having the same issues.

got tk wine mono python-pip python-virtualenv steam protonup-qt and proton tricks all installed to make it as far as i do get.. little baffling. have tried it on 3 different games now and the exact same issue happens with all 3.

**Comment by calvyb** [comment]
Update: I think ive found a possible culprit.

My linux distro is Arch Running KDE Plasma. and i've discovered it only freezes and crashes on Wayland. If i logout and login with X11 instead of wayland wemod doesnt freeze and works as i would expect. and the game runs. Frame rate is terrible but it's progress.

switched between x11 and wayland several times and the behaviour is repeatable and consistent. wayland always freezes wemod but the game runs buttery smooth. x11 wemod always works just with terrible framerates.

so i now have 2 avenues to pursue. either figure a way to fix it on wayland, or figure how to improve the framerates on x11.

**Comment by calvyb** [comment]
UPDATE: out of curiosity as my laptop is AMD  and wondered if it could be a nvidia issue. I Decided I'd stick Arch with KDE on the laptop and got wemod working perfectly once again. even in wayland. Using AMDRadeon drivers. Integrated AMD GPU. So it's possible it's a nvidia on wayland driver issue. As nvidia on x11 works fine.. 

Just thought I'd post this update as it may be helpful to someone.. or if someone stumbles across and has it working on nvidia could offer insight into how.

**Comment by HelpMePleasepls** [comment]
So I am also on NVIDIA (latest beta driver), OpenSUSE Tumbleweed, and I am running into the same issue on Wayland. Now, I've noticed that wayland doesn't actually freeze. For me, it refreshes and I'm able to interact with it. It just takes about 2 minutes or more for it to update based on what I selected.

**Comment by marvin1099** [comment]
As mentioned 

> So I am also on NVIDIA (latest beta driver), OpenSUSE Tumbleweed, and I am running into the same issue on Wayland. Now, I've noticed that wayland doesn't actually freeze. For me, it refreshes and I'm able to interact with it. It just takes about 2 minutes or more for it to update based on what I selected.

Try x11, other than that, no solution was discovered yet.

**Comment by HelpMePleasepls** [comment]
Yeah, I've read the comments and I've also discovered that x11 is working fine. However, wemod appears to be completely operable on wayland despite the refresh issues. I'm able to toggle the cheats on and off and have the audible ding play at the exact moment I activate it. If the user has some patience, all they have to do is navigate through wemod to their game, hit "Play Game", wait some more until it says "Playing game" and then take screenshots of your available cheats and store them somewhere so that you don't have to rely on wemod's slow refresh issue. Then, wait some more until it processes that, go back to your game, and now you're able to hit the hotkeys for the cheats and they'll work.

**Comment by marvin1099** [comment]
Ok so this has been a long running issue and i pretty sure the wemod launcher can't actually fix this issue.
The reason for this is that the wemod launcher just uses steam and wine behind the scenes 
and the pretty shure the issue lies in the support of wayland from wine and steam (+nvidia).
So there is no really way to fix this right now and keeping this issue around is also not that useful,
since if it is not a launcher issue, then if this gets fixed it will be by wine and steam (+nvidia).
So if there is no objection to this i will close this and add a help page about this in the wiki.

**Comment by HelpMePleasepls** [comment]
> Ok so this has been a long running issue and i pretty sure the wemod launcher can't actually fix this issue. The reason for this is that the wemod launcher just uses steam and wine behind the scenes and Im pretty shure the issue lies in the support of wayland from wine and steam (+nvidia). So there is no real way to fix this right now and keeping this issue around is also not that useful, since if it is not a launcher issue, then if this gets fixed it will be by wine and steam (+nvidia). So if there is no objection to this i will close this and add a help page about this in the wiki.
> 
> Thee wiki page is already online and can be seen [right here](https://github.com/DeckCheatz/wemod-launcher/wiki/Wemod-on-NVIDIA-Wayland-with-Steam).

Sure, you can close the issue.

**Comment by marvin1099** [comment]
I have added this as you requested, can hurt to have that after all.

**Comment by marvin1099** [comment]
I close this for now as mentioned.

**Comment by Madic-** [comment]
Is it possible to force the application to use xwayland? If yes, how? I'm also on KDE Plasma Wayland with nvidia

**Comment by marvin1099** [comment]
I have never done thus myself, chatgpt suggests that you use the command `env GDK_BACKEND=x11 WAYLAND_DISPLAY= APP-PATH-HERE` to run gdk with x11 and use a emtpy Wayland session, which apparently may also result in the app being run in xwayland.

Realy you should just ask a assistant like Hugging Chat, chatgpt or use the classic websearch with something like google, duckduckgo or brave-search.

You probably won't have lots of luck getting help for running apps with xwayland here since I'm realy the only active developer right now and I just don't use Wayland, so you probably have better luck searching the internet.

**Comment by marvin1099** [comment]
> I have never done thus myself, chatgpt suggests that you use the command `env GDK_BACKEND=x11 WAYLAND_DISPLAY= APP-PATH-HERE` to run gdk with x11 and use a emtpy Wayland session, which apparently may also result in the app being run in xwayland.
> 
> Realy you should just ask a assistant like Hugging Chat, chatgpt or use the classic websearch with something like google, duckduckgo or brave-search.
> 
> You probably won't have lots of luck getting help for running apps with xwayland here since I'm realy the only active developer right now and I just don't use Wayland, so you probably have better luck searching the internet.


But @Madic- if you can figure out how exaxtly to do it i will gladly add any and all infos to the [wiki page](https://github.com/DeckCheatz/wemod-launcher/wiki/Wemod-on-NVIDIA-Wayland-with-Steam) to help anyone else on the future that has the same questions.

And also it is possible to do this I know that.
Users have reported getting this to work with xwayland, so it is doable I just don't know how.
The suggestion from chatgpt may work you can still try that (your app path will probably be "steam").

**Comment by calvyb** [comment]
This issue appears to be resolved.Not certain whether nvidia drivers the latest proton ge. Or something else.A recent system update (sudo pacman -Syu) seems to have everything working. Sadly I can't pinpoint exactly which thing that was updated fixed it.Sent from my Galaxy
-------- Original message --------From: Marvin1099 ***@***.***> Date: 15/11/2024  22:00  (GMT+00:00) To: DeckCheatz/wemod-launcher ***@***.***> Cc: calvyb ***@***.***>, Mention ***@***.***> Subject: Re: [DeckCheatz/wemod-launcher] [BUG]: On nvidia wayland the launcher never finishes steam and steam does nothing (Issue #108) 

I have never done thus myself, chatgpt suggests that you use the command env GDK_BACKEND=x11 WAYLAND_DISPLAY= APP-PATH-HERE to run gdk with x11 and use a emtpy Wayland session, which apparently may also result in the app being run in xwayland.
Realy you should just ask a assistant like Hugging Chat, chatgpt or use the classic websearch with something like google, duckduckgo or brave-search.
You probably won't have lots of luck getting help for running apps with xwayland here since I'm realy the only active developer right now and I just don't use Wayland, so you probably have better luck searching the internet.

But @Madic- if you can figure out how exaxtly to do it i will gladly add any and all infos to the wiki page to help anyone else on the future that has the same questions.
And also it is possible to do this I know that.
Users have reported getting this to work with xwayland, so it is doable I just don't know how.
The suggestion from chatgpt may work you can still try that (your app path will probably be "steam").

**Comment by marvin1099** [comment]
Well at least you found a solution.
If you can pinpoint anything say so.
